[tool.poetry]
name = "oxio-geofeed"
version = "0.1.0"
description = ""
authors = ["Vincent Charpentier <vincent@oxio.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ipaddr = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
